localStorage.clear();
const employees = [
  {
    id: 1,
    first_name: "Amit",
    email: "amit.sharma@example.com",
    password: "123",
    tasks: [
      {
        active_task: true,
        failed_task: false,
        completed_task: false,
        new_task: true,
        task_title: "Update Software",
        task_description: "Update the software to the latest version.",
        task_date: "2025-01-05",
        assign_to: "amit",
        category: "IT",
      },
      {
        active_task: false,
        failed_task: true,
        completed_task: false,
        new_task: false,
        task_title: "Fix Bugs",
        task_description: "Fix the bugs reported by the QA team.",
        task_date: "2025-01-04",
        assign_to: "amit",
        category: "Development",
      },
      {
        active_task: true,
        failed_task: false,
        completed_task: true,
        new_task: false,
        task_title: "Create Report",
        task_description: "Create the monthly report for the management.",
        task_date: "2025-01-03",
        assign_to: "amit",
        category: "Administration",
      },
    ],
    task_numbers: {
      active: 2,
      failed: 1,
      completed: 1,
      new: 1,
    },
  },
  {
    id: 2,
    first_name: "Priya",
    email: "priya.kapoor@example.com",
    password: "123",
    tasks: [
      {
        active_task: true,
        failed_task: false,
        completed_task: false,
        new_task: true,
        task_title: "Design Logo",
        task_description: "Design a new logo for the client.",
        task_date: "2025-01-05",
        assign_to: "priya",
        category: "Design",
      },
      {
        active_task: false,
        failed_task: true,
        completed_task: false,
        new_task: false,
        task_title: "Prepare Presentation",
        task_description: "Prepare the presentation for the upcoming meeting.",
        task_date: "2025-01-04",
        assign_to: "priya",
        category: "Sales",
      },
      {
        active_task: true,
        failed_task: false,
        completed_task: true,
        new_task: false,
        task_title: "Review Contract",
        task_description: "Review the contract and provide feedback.",
        task_date: "2025-01-03",
        assign_to: "priya",
        category: "Legal",
      },
    ],
    task_numbers: {
      active: 2,
      failed: 1,
      completed: 1,
      new: 1,
    },
  },
  {
    id: 3,
    first_name: "Rahul",
    email: "rahul.verma@example.com",
    password: "123",
    tasks: [
      {
        active_task: true,
        failed_task: false,
        completed_task: false,
        new_task: true,
        task_title: "Conduct Training",
        task_description: "Conduct training sessions for the new employees.",
        task_date: "2025-01-05",
        assign_to: "rahul",
        category: "HR",
      },
      {
        active_task: false,
        failed_task: true,
        completed_task: false,
        new_task: false,
        task_title: "Organize Event",
        task_description: "Organize the annual company event.",
        task_date: "2025-01-04",
        assign_to: "rahul",
        category: "Event Management",
      },
      {
        active_task: true,
        failed_task: false,
        completed_task: true,
        new_task: false,
        task_title: "Update Policies",
        task_description: "Update the company policies and distribute them.",
        task_date: "2025-01-03",
        assign_to: "rahul",
        category: "Administration",
      },
    ],
    task_numbers: {
      active: 2,
      failed: 1,
      completed: 1,
      new: 1,
    },
  },
  {
    id: 4,
    first_name: "Anjali",
    email: "anjali.singh@example.com",
    password: "123",
    tasks: [
      {
        active_task: true,
        failed_task: false,
        completed_task: false,
        new_task: true,
        task_title: "Market Research",
        task_description: "Conduct market research for the new product.",
        task_date: "2025-01-05",
        assign_to: "anjali",
        category: "Marketing",
      },
      {
        active_task: false,
        failed_task: true,
        completed_task: false,
        new_task: false,
        task_title: "Develop Strategy",
        task_description: "Develop a marketing strategy for the new campaign.",
        task_date: "2025-01-04",
        assign_to: "anjali",
        category: "Marketing",
      },
      {
        active_task: true,
        failed_task: false,
        completed_task: true,
        new_task: false,
        task_title: "Analyze Data",
        task_description: "Analyze the sales data and create a report.",
        task_date: "2025-01-03",
        assign_to: "anjali",
        category: "Data Analysis",
      },
    ],
    task_numbers: {
      active: 2,
      failed: 1,
      completed: 0,
      new: 2,
    },
  },
  {
    id: 5,
    first_name: "Rohit",
    email: "rohit.kumar@example.com",
    password: "123",
    tasks: [
      {
        active_task: true,
        failed_task: false,
        completed_task: false,
        new_task: true,
        task_title: "Customer Support",
        task_description: "Handle customer support queries.",
        task_date: "2025-01-05",
        assign_to: "rohit",
        category: "Customer Service",
      },
      {
        active_task: false,
        failed_task: true,
        completed_task: false,
        new_task: false,
        task_title: "Inventory Management",
        task_description: "Manage the inventory and stock levels.",
        task_date: "2025-01-04",
        assign_to: "rohit",
        category: "Logistics",
      },
      {
        active_task: true,
        failed_task: false,
        completed_task: true,
        new_task: false,
        task_title: "Update Website",
        task_description: "Update the company website with new information.",
        task_date: "2025-01-03",
        assign_to: "rohit",
        category: "IT",
      },
    ],
    task_numbers: {
      active: 2,
      failed: 1,
      completed: 1,
      new: 1,
    },
  },
];

const admin = [
  {
    id: "admin1",
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  // const data=localStorage.getItem("employees");
  // console.log(data);
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));
  return { employees, admin };
};
